version: "3.9"
services:
  db:
    image: postgres:13-alpine
    volumes: 
      - db_data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  dbviewer: 
    image: adminer:latest
    restart: always
    ports: 
      - "8080:8080"
    depends_on: 
      - db
volumes:
  db_data: